// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNl-Xu6m-0LcNUQkiHVnlC5d5CaILDL1U',
    appId: '1:422032729764:web:d2abbcd3452b4e5d872831',
    messagingSenderId: '422032729764',
    projectId: 'qteam-5d444',
    authDomain: 'qteam-5d444.firebaseapp.com',
    storageBucket: 'qteam-5d444.firebasestorage.app',
    measurementId: 'G-YNTGZXHGKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwUv6jI5wr7Si4TCH8r3FYVI_jYCR5CLQ',
    appId: '1:422032729764:android:9e00d4440bdb94ce872831',
    messagingSenderId: '422032729764',
    projectId: 'qteam-5d444',
    storageBucket: 'qteam-5d444.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAemkHpgwnYNvqjpwanRNravoC4djMlqpU',
    appId: '1:422032729764:ios:41344113a3681fc7872831',
    messagingSenderId: '422032729764',
    projectId: 'qteam-5d444',
    storageBucket: 'qteam-5d444.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAemkHpgwnYNvqjpwanRNravoC4djMlqpU',
    appId: '1:422032729764:ios:41344113a3681fc7872831',
    messagingSenderId: '422032729764',
    projectId: 'qteam-5d444',
    storageBucket: 'qteam-5d444.firebasestorage.app',
    iosBundleId: 'com.example.projectapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNl-Xu6m-0LcNUQkiHVnlC5d5CaILDL1U',
    appId: '1:422032729764:web:122fce2a9f3399cb872831',
    messagingSenderId: '422032729764',
    projectId: 'qteam-5d444',
    authDomain: 'qteam-5d444.firebaseapp.com',
    storageBucket: 'qteam-5d444.firebasestorage.app',
    measurementId: 'G-WYE3NRD7CY',
  );

}